### PR TITLE
Update KDE Runtime to 6.6

### PR DESCRIPTION
**Pull request by Zishan-Rahman**
The automated test build _might_ fail to locate the new SDK, as it was only _just_ recently added here: flathub/buildbot-config#88

If it _does_ fail, we can try building it again in an hour or two.

### CODE REVIEW

**Comment by Lunarequest** [comment]
can you rebase this on #62?

**Comment by Zishan-Rahman** [comment]
> can you rebase this on #62?

Can do :+1:

**Comment by Zishan-Rahman** [comment]
> > can you rebase this on #62?
> 
> Can do 👍

Just did :+1:

**Comment by Zishan-Rahman** [comment]
I guess we'll try again in an hour or two.

**Comment by Zishan-Rahman** [comment]
bot, build

**Comment by Lunarequest** [comment]
bot, build

**Comment by Zishan-Rahman** [comment]
https://github.com/flathub/org.texstudio.TeXstudio/issues/170#issuecomment-1769105181

**Comment by bbhtt** [comment]
6.6 isn't published due to some technical isses. Just because the buildbot PR was merged and the upstream branch is available doesn't mean it is published.

Please have patience and make sure it is available before issuing a build (this will show if it is published)

```
flatpak remote-info flathub --system org.kde.Sdk//6.6
```

**Comment by bbhtt** [comment]
6.6 is now available on Flathub

**Comment by Zishan-Rahman** [comment]
bot, build

**Comment by Zishan-Rahman** [comment]
bot, build

**Comment by Lunarequest** [comment]
I'm not going to be able to merge this for a bit. Will be traveling

**Comment by Zishan-Rahman** [comment]
```bash
git fetch -f -t https://github.com/flathub/org.strawberrymusicplayer.strawberry refs/pull/63/head --progress
 in dir /var/lib/buildbot-master/master/workers/MasterWorker8/Builds/build (timeout 1200 secs)
 watching logfiles {}
 argv: [b'git', b'fetch', b'-f', b'-t', b'https://github.com/flathub/org.strawberrymusicplayer.strawberry', b'refs/pull/63/head', b'--progress']
 using PTY: False
fatal: unable to access 'https://github.com/flathub/org.strawberrymusicplayer.strawberry/': gnutls_handshake() failed: The TLS connection was non-properly terminated.
program finished with exit code 128
```

No idea why _that_'s happening now :thinking:

**Comment by Zishan-Rahman** [comment]
bot, build

**Pull request merged**
