### PR TITLE
update to 1.1.0

### PR DESCRIPTION
**Pull request by mikelpr**
- update strawberry to 1.1.0
- update boost to 1.85.0, TagLib to 1.13.1, vlc to 3.0.21 and libusb to 1.0.27

didn't update KDE SDK to 6.7 as I kept hitting build errors, and didn't know how to update protobuf since protobuf-cpp is gone from their releases

### CODE REVIEW

**Comment by mikelpr** [comment]
[fail-6.7.log](https://github.com/user-attachments/files/16274220/fail-6.7.log)
attaching log of build failure when trying to build with org.kde.Sdk//6.7

builds just fine with 6.6 which I kept within this PR

**Comment by Zishan-Rahman** [comment]
@mikelpr The test build failed purely because of a AppStream validation error. I have a PR open, https://github.com/flathub/org.strawberrymusicplayer.strawberry/pull/81/, that addresses said error (it also specifies that the Flatpak is unofficial, as well as resolving https://github.com/flathub/org.strawberrymusicplayer.strawberry/issues/76). You may want to either merge my changes into your PR or rebase them onto it. Once you do whatever you think is best (I don't mind either merging or rebasing), I can close https://github.com/flathub/org.strawberrymusicplayer.strawberry/pull/81/, and once _your_ PR is merged after that, https://github.com/flathub/org.strawberrymusicplayer.strawberry/issues/76 can also be closed.

**Comment by mikelpr** [comment]
@Zishan-Rahman, no problem with the ping and taking the liberty to do so back :) oddly I'm getting crashes after selecting folders via portals, like on Playlist -> Add folder, and Transcode dialog -> Select (destination), so let me check what's up with that before going further

**Comment by mikelpr** [comment]
also, apparently flathubbot took care of doing the round of updates with PR #83 lol. it just missed updating TagLib and the shared-modules (for libusb)

**Pull request closed without merging**
